import java.util.HashMap;
import java.util.*;
final int SCREENX = 1280;
final int SCREENY = 720;
public static String value;
public static String collumn;
public static String upperValueString;
public static TextWidget searchBar; 
public static TextWidget searchBarC;
 public static TextWidget valueRange;
