//Antoni Zapedowski
class Space_Object {
  String jcat;
  String satcat;
  String piece;
  String type;
  String name;
  String plname;
  String lDate;
  String parent;
  String sDate;
  String primary;
  String dDate;
  String status;
  String dest;
  String owner;
  String state;
  String manufac;
  String bus;
  String motor;
  int mass;
  String massFlag;
  int dryMass;
  String dryFlag;
  int totMass;
  String totFlag;
  String lenght;
  String lFlag;
  double diameter;
  String dFlag;
  String span;
  String spanFlag;
  String shape;
  String oDate;
  int perigee;
  String PF;
  int apogee;
  String AF;
  String inc;
  String ifa;
  String opOrbit;
  String qQual;
  String altNames;
  LocalDate launchDate;
  int decommissionedYear;
  boolean isNullDate;

  Space_Object(String jcat, String satcat, String piece, String type, String name, String plname, String lDate, String parent, String sDate, String primary, String dDate, String status, String dest, String owner, String state, String manufac, String bus, String motor, int mass, String massFlag, int dryMass, String dryFlag, int totMass, String totFlag, String lenght, String lFlag, double diameter, String dFlag, String span, String spanFlag, String shape, String oDate, int perigee, String PF, int apogee, String AF, String inc, String ifa, String opOrbit, String qQual, String altNames, LocalDate launchDate, int decommissionedYear, boolean isNull) {
    this.jcat = jcat;
    this.satcat = satcat;
    this.piece = piece;
    this.type = type;
    this.name = name;
    this.plname = plname;
    this.lDate = lDate;
    this.parent = parent;
    this.sDate = sDate;
    this.primary = primary;
    this.dDate = dDate;
    this.status = status;
    this.dest = dest;
    this.owner = owner;
    this.state = state;
    this.manufac = manufac;
    this.bus = bus;
    this.motor = motor;
    this.mass = mass;
    this.massFlag = massFlag;
    this.dryMass = dryMass;
    this.dryFlag = dryFlag;
    this.totMass = totMass;
    this.totFlag = totFlag;
    this.lenght = lenght;
    this.lFlag = lFlag;
    this.diameter = diameter;
    this.dFlag = dFlag;
    this.span = span;
    this.spanFlag = spanFlag;
    this.shape = shape;
    this.oDate = oDate;
    this.perigee = perigee;
    this.PF = PF;
    this.apogee = apogee;
    this.AF = AF;
    this.inc = inc;
    this.ifa = ifa;
    this.opOrbit = opOrbit;
    this.qQual = qQual;
    this.altNames = altNames;
    this.launchDate = launchDate;
    this.decommissionedYear = decommissionedYear;
    this.isNullDate = isNull;
}

// a dummy object 
Space_Object() { 
   this.jcat = "";
    this.satcat = "";
    this.piece = "";
    this.type = "";
    this.name = "";
    this.plname = "";
    this.lDate = "";
    this.parent = "";
    this.sDate = "";
    this.primary = "";
    this.dDate = "";
    this.status = "";
    this.dest = "";
    this.owner = "";
    this.state = "";
    this.manufac = "";
    this.bus = "";
    this.motor = "";
    this.mass = -2137;
    this.massFlag = "";
    this.dryMass = -2137;
    this.dryFlag = "";
    this.totMass = -2137;
    this.totFlag = "";
    this.lenght = "";
    this.lFlag = "";
    this.diameter = -2137;
    this.dFlag = "";
    this.span = "";
    this.spanFlag = "";
    this.shape = "";
    this.oDate = "";
    this.perigee = -2137;
    this.PF = "";
    this.apogee = -2137;
    this.AF = "";
    this.inc = "";
    this.ifa = "";
    this.opOrbit = "";
    this.qQual = "";
    this.altNames = "";
    this.launchDate = null;
}

}
